### ISSUE TITLE
Display an Error when a User doesn't Exist when viewing profiles

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#114]
I've noticed that in TW Blue, when viewing user details, if a user doesn't exist, rather than displaying an error message, it displays an empty window that can't be closed, and the Twitter API returns a 404 (not found) error. Would it be possible to generate an error saying 'That user does not exist" if this occurs?

**Comment by jmdaweb** [comment]
This is an error in your translation. In english or spanish we see an error message (“The user doesn’t exist”). @manuelcortez, do you know any method to validate the po files?


From: Mohamed Al-Hajamy
Sent: Wednesday, February 1, 2017 2:15 AM
To: manuelcortez/TWBlue
Cc: Subscribed
Subject: [manuelcortez/TWBlue] Display an Error when a User doesn't Exist when viewing profiles (#114)


I've noticed that in TW Blue, when viewing user details, if a user doesn't exist, rather than displaying an error message, it displays an empty window that can't be closed, and the Twitter API returns a 404 (not found) error. Would it be possible to generate an error saying 'That user does not exist" if this occurs?

**Comment by manuelcortez** [comment]
this is not a translation bug, I have reproduced it in the English version of the client. About validating translations, I don't think it's possible, or am not sure how.
