### ISSUE TITLE
Suspended Accounts Error Displays in Incorrect Cases

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#155]
The suspended account error that displays when you try to open the timeline of a suspended user is sometimes displayed when it shouldn't be.
### Steps to Reproduce.
* Try something like disconnecting your Internet connection.
### Expected.
Either nothing happens, or an error explaining that you don't have an Internet connection is displayed.
### Actual.
The suspended user error is displayed.

**Comment by manuelcortez** [comment]
There's no way to get info about a suspended Account. In case of a suspended account, twitter just don't return that object. What I had to do is get the response code, and if it's not 404 (not found) or 403 (prohibited) then it should be suspended. However, when internet is not working we will not get a response code, so that's why it matches the suspended account dialog.

You can read more about this [here](https://dev.twitter.com/rest/reference/get/users/lookup) and [here](https://dev.twitter.com/rest/reference/get/users/show)

**Comment by Mohamed00** [comment]
So is this something you can't fix? If so, I'll close this.
