### ISSUE TITLE
traceback when Playing Audio from Dropbox Links

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#159]
### Steps to Reproduce.
1. Try to play audio from Dropbox.
### Expected.
Audio should play.
### Actual.
A can't open the file traceback is displayed, even if the link works.
Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 70, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 88, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 1192, in audio
    self.get_current_buffer().audio()
  File "C:\twblue\src\controller\buffersController.py", line 638, in audio
    sound.URLPlayer.play(url, self.session.settings["sound"]["volume"])
  File "C:\twblue\src\sound.py", line 143, in play
    self.stream = sound_lib.stream.URLStream(url=self.url)
  File "C:\twblue\src\sound_lib\stream.py", line 60, in __init__
    handle = bass_call(BASS_StreamCreateURL, url, offset, flags, self.downloadproc, user)
  File "C:\twblue\src\sound_lib\main.py", line 50, in bass_call
    raise BassError(code, get_error_description(code))
sound_lib.main.BassError: 2, can't open the file

**Comment by jmdaweb** [comment]
We think that bass library has problems playing these links from slow Internet connections. We tried changing timeouts, but It didn't work. This issue is very difficult to reproduce.

**Comment by Mohamed00** [comment]
Odd? For me, the can't open the file traceback always occurs with Dropbox links. Wouldn't it be a timeout?

**Comment by manuelcortez** [comment]
Hello,

It seems we had a few issues with dropbox links and other kind of URLS. Recently I had some issues when trying to play a live stream. Basically in the url_shortener package there is a call to requests.get(), wich will download the full stream but without giving the returned value, so that makes the client to freeze while waiting for the value to be returned. I have fixed that. Now this function only returns the normal URL and it should be fine for radio streams and other audios.

Regarding dropbox shared links, they works fine here (after that fix). Please be sure that you put ?dl=1 instead 0 at the end of the link, so it will force a direct download.
