### ISSUE TITLE
UX: Unified "new buffer" dialog

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#18]
In the buffer menu, we should create one main dialog which has all the features of the dialogs for creating user timeline buffers, user favorites buffers, and trending topics buffers, as well as any other user-defined buffer types (obviously except for conversations since those are dependent on the focused tweet and it wouldn't make sense for that to go there).
At the moment, "new buffer..." calls the new user timeline dialog. The new_buffer method needs to be written. @manuelcortez I think this is another GUI project for you.

**Comment by manuelcortez** [comment]
I think it is not possible to mix the trending topic buffer with all the other buffers, because when you create a trend buffer, you will see a list with a two radio buttons for selecting the city or country for getting the trends. So you must open the new buffer, select the trend in the radio button, press OK, then select the things for create the buffer. And it is not more usable than the current implementation.

**Comment by codeofdusk** [comment]
Yes you can. Make it a tabbed dialog, or a dialog with a radio button for “user timeline buffer”, “favorites buffer” and “trending topics buffer”.

Bill

**Comment by manuelcortez** [comment]
It will not be very usable, you will get a overloaded dialog with many different options and tipical users may be confused by applying this change.
