### ISSUE TITLE
Move Client Filter in to Filter Dialog

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#182]
Since the ability to ignore tweets by client is technically a filter, shouldn't it also be moved to the create a filter dialog? And also while we're on the topic of filters, I don't see a way to view the filters applied to a buffer, and the remove button appears even if no languages are in the filter.

**Comment by manuelcortez** [comment]
Hi,
Firstly, I think is worth mentioning that #102 is not closed yet, I just added the GUI elements (and populated language options) to the program. It doesn't create any config in client settings and stuff. I just added the "view" in the MVC pattern dessign we're using. Therefore we cannot move client filtering stuff (wich is already working) to this filter section, where everything is just a window and nothing else. Once finished, we will have to talk about how to integrate client filters to this new way for filtering tweets in buffer, but I think at this time is not possible.
Secondly, it would be nice to re-open an issue (in case it's closed) for talking about the same topic instead creating a new one. This one, for example, wouldn't be needed. You could just comment in #102 (filters, everything related to them and its implementation may be relevant there). Otherwise we would close the original isue and every possible regression will be a new issue.
