### ISSUE TITLE
TWBlue broken after last source update

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#201]
Just not loading after last source update, after youtube support. Dont know what to send, because log files not present.

**Comment by manuelcortez** [comment]
Make sure you have the needed modules introduced in the last changeset. For the last commits to work, you will need the following:

1. Youtube-dl and python-vlc installed as modules.
2. VLC media player. (python-vlc will needs libvlc.dll and libvlccore.dll and for now we haven't supplied these libraries, yet).

**Comment by agasoft** [comment]
Ah, right direction. How to install or get those? I forgot.

**Comment by manuelcortez** [comment]
pip install youtube-dl python-vlc

And vlc itself should be easy to find in google :)

**Comment by agasoft** [comment]
Installed youtube module and VLC on my computer, but still not working. DO I need to paste DLL somewhere or VLC installation should be enough?

**Comment by agasoft** [comment]
Ok.
To summerize:
I installed youtube vlc module, installed vlc player.
Then I am getting this in stderr.log:
WindowsError: [Error 126] The specified module could not be found.
But if I copy those 2 DLLS in Python directory, I am getting:
WindowsError: [Error 193] %1 is not a valid Win32 application.
What should I do and what is wrong?

**Comment by jmdaweb** [comment]
Hello.

Ensure that your dlls are for the same architecture as Python. If you use Python for 32-bit, copy libvlc and libvlccore from vlc for 32 bits. Otherwise, copy the x64 ones. Downloading vlc media player in zip format can help, so you haven't to install both versions in your computer.

Regards.

El 21/02/2018 a las 9:54, agasoft escribió:

Ok.
To summerize:
I installed youtube vlc module, installed vlc player.
Then I am getting this in stderr.log:
WindowsError: [Error 126] The specified module could not be found.
But if I copy those 2 DLLS in Python directory, I am getting:
WindowsError: [Error 193] %1 is not a valid Win32 application.
What should I do and what is wrong?

**Comment by agasoft** [comment]
Great. I just forgot to install VLC 64, but now when I did it python found libraries itself. Thanks, its working now as should. It was my fault.

**Comment by jmdaweb** [comment]
Enjoy the new changes!
