### ISSUE TITLE
Report to Braille might disrupt at times

### ISSUE THREAD

**Issue by vincent-lg** [manuelcortez/TWBlue#203]
For users like me who only use Braille with their screen readers, the ability of TWBlue to report in Braille is both a blessing and a problem at times.  When working or reading (possibly outside of the window), having reports about upcoming tweets for instance will completely hide the older activity for the alert delay.  That's short, but with a lot of following tweets, that might get pretty problematic at times.  I suggest a new option in the global settings (preferably a new tab) to control TTS a bit more, both speech and Braille being separated.  I would assume even a single checkbox to enable/disable text reporting in Braille would be sufficient, at least for me.

Thank you for your great work!

**Comment by manuelcortez** [comment]
Hi,

thanks for reporting this issue! As a speech only user I really didn't know anything about how it can be a problem for users who rely only in Braille. I'd like to ask a few questions thought, in order to being able to help a bit more in this situation:

1. You said would be enough to have an option for disabling Braille or Speech reports. Would not be better to being able to mute every message separately? It would allow you to control what is going to be sent to the Braille display or tts. I thought in getting a list of the most common messages reported to users and allowing people to select wether they want them to be reported or not.
2. About Braille, do you think should messages be reported automatically by default?

**Comment by vincent-lg** [comment]
1. Actually, that's why I said "should be enough".  Your solution would be really great, to be able to decide what type of messages should be spoken/displayed.  You probably already figured that part out, but the two problems with this strategy being: muting everything should be quite simple, and, of course, it would make things harder for you in development.
2. Yes, I think automatic reporting in Braille should be the default.  Very few users like me rely exclusively on Braille output and can be taken aback by systematic Braille reporting.  Users who have Braille as a supplementary output method welcome automatic reporting.

**Comment by manuelcortez** [comment]
OK, according to your reply (and others' feedback in twitter), I will add a check for allowing or muting speech and braille automatic reports. Probably thihs won't take effect in the next snapshot because everything is going to be built soon, but may be available in the next one.
