### ISSUE TITLE
Change behavior of autoread for buffers

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#221]
Currently as we use the Streaming API, we support allowing buffers to read automatically new items as soon as they are added to the list. However, due to streaming functionality being deprecated, we should modify the behavior of buffer autoreading. I think we may implement one of the following options:

1. When a buffer will be updated, it will read automatically the number of new items retrieved, if said number is greater than 0.
2. Remove this option completely.

thoughts?

**Comment by lukaszgo1** [comment]
As a user i will vote for option one because:
1. When you have one or more timelines/searches open the sound indicating update is the same, so without spoken info you have no idea  in which buffer something happened.
2. For users of hardware speech synthesizer's such as myself the only way of being notified of a new event is a speech message the same goes probably for deaf blind people who uses only braille display.
