### ISSUE TITLE
When relative timestamps are unchecked the time of a tweet is shifted an hour back.

### ISSUE THREAD

**Issue by lukaszgo1** [manuelcortez/TWBlue#267]
## STR
1. find a tweet and take note of the time for example 14 minutes ago.
2. In the account settings uncheck relative timestamps.
3. Restart TWBlue and check time of the tweet.
## Expected.
The proper time should be shown.
## Actual
the time is shifted an hour back.
It happens for every item regardless of the timeline. It makes unchecking relative timestamps pretty useless at the moment.

**Comment by sukiletxe** [comment]
Cannot reproduce. I don't use relative timestamps. Make sure to configure your timezone in Twitter settings.

**Comment by lukaszgo1** [comment]
Setting my timezone in twitter settings fixed it. It needs to be clearly stated in TWBlue documentation though, because no other twitter client seems to require it to calculate time properly.

**Comment by lukaszgo1** [comment]
@manuelcortez May I ask why you don't want to document the fact, that proper timezone setting on the Twitter website is necessary to make this feature working? In my view it is small price to pay for not having to close another issue about this in the future

**Comment by manuelcortez** [comment]
@lukaszgo1 First of all, I'm sorry if it seemed rude to you. I didn't meant to close  this issue just because didn't want to document it. I agree it should be documented, though right now I am not the person that will do so. Documentation needs lots of updates (removing everything about streaming endpoint, talking about new features like filters, youtube playback (or media playback in general), changes to direct messages, autoreading, you get it). I'll open a new milestone regarding documentation updates in the next days, where the topic of the issue you have reported, and other changes to documentation, will be discussed. Also, if you or someone else is up to contribute to the documentation, I'd be more than happy to accept pull requests. Right now I don't have spare time to spend in software development, and even less in documentation (plus my english grammar, that's not a good combo :)).

**Comment by lukaszgo1** [comment]
> 
> 
@manuelcortez wrote:
> @lukaszgo1 First of all, I'm sorry if it seemed rude to you. I didn't meant to close this issue just because didn't want to document it.

It definitely didn't. I am just used to different way of managing bug reports i.e assigning to the milestones instead of closing.
