### ISSUE TITLE
Python 3: Spell Check Does Not Launch

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#296]
### Steps to reproduce.
1. Compose and tweet and try to launch spell check.
### Expected.
The spell checker launches.
### Actual.
The spell checker does not launch and the following traceback is displayed.
Traceback (most recent call last):
  File "c:\twblue\src\controller\messages.py", line 116, in spellcheck
    checker = SpellChecker.spellchecker.spellChecker(text, "")
  File "c:\twblue\src\extra\SpellChecker\spellchecker.py", line 26, in __init__
    dict_path = enchant.get_param("enchant.myspell.dictionary.path")
  File "C:\Program Files\Python37\lib\site-packages\enchant\__init__.py", line 479, in get_param
    return name.decode(_e.broker_get_param(self._this,name.encode()))
  File "C:\Program Files\Python37\lib\site-packages\enchant\utils.py", line 170, in decode
    return value.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by Mohamed00** [comment]
I tried using pyenchant from pip, and the traceback is different.
Traceback (most recent call last):
  File "c:\twblue\src\controller\messages.py", line 116, in spellcheck
    checker = SpellChecker.spellchecker.spellChecker(text, "")
  File "c:\twblue\src\extra\SpellChecker\spellchecker.py", line 35, in __init__
    self.dict = enchant.DictWithPWL(languageHandler.curLang[:2], paths.config_path("wordlis
t.dict"))
TypeError: config_path() takes 0 positional arguments but 1 was given

**Comment by manuelcortez** [comment]
this last comment describes an issue that has already been fixed, I mean about the config_path being used incorrectly. However  the spell checking still will refuse to work because in the source code, the module expects all dictionaries to live in the user config directory, as opposed to the default enchant folder. I recall this was done this way because I wanted to offer people spelling dictionaries as separate (extra) downloads, so we will no longer include those in the TWBlue packages, thus freeing up some important space in the final bundles. See #208 for more details about this.
theoretically, if you create a folder inside the config directory called dicts, and drop there all dictionaries for the languages you like, that will work normally.

**Comment by Mohamed00** [comment]
Unfortunately it doesn't seem to, it still fails to launch here.
