### ISSUE TITLE
Is running on Mac (even from source) supported?

### ISSUE THREAD

**Issue by colegleason** [manuelcortez/TWBlue#311]
Hi, I'd like to try out TWBlue on a Mac, is there a version that supprts it, or does it call too many windows specific packages?

**Comment by manuelcortez** [comment]
Hi there,
Currently we don't have anyone who would be willing to put efforts in a mac compatible code. So far,  TWBlue is only compatible with Windows systems, mainly due to some packages (winpaths, pywin32, win_inet) and techniques (most notably the invisible interface would not be easily supported). Also, in case of adding support for Mac, we would need to write a compatible graphical interface, due to WX not being accessible enough to offer the same experience on it.

**Comment by colegleason** [comment]
Thanks for the explanation!
