### ISSUE TITLE
DMS aren't updated instently as it should

### ISSUE THREAD

**Issue by Ramon-Salazar** [manuelcortez/TWBlue#334]
The DM buffer is counted like Home and Mentions and it updates every minute or more according to the selection, but DMS updates every 2 minutes which is strange

DMS  buffer should be updated derectly

**Comment by jmdaweb** [comment]
Hi Ramón,
There is nothing we can do to update this buffer in the same way other buffers are updated. Twitter API applies a delay to direct messages, so they are received later than you receive them in the native Twitter apps, for example.
Regards.

**Comment by rkingett** [comment]
Twitter has made it even harder to get instant DM's and even third party functionality without, well, [paying them a boatload.](https://developer.twitter.com/en/pricing) Mastodon would be a better investment, I mean, in general. But if you want this, you gotta donate to the TW Blue folks because now, they have to pay for this feature. But even then, getting this would be nearly impossible, thanks to Twitter.
