### ISSUE TITLE
twBlue does not run

### ISSUE THREAD

**Issue by guredora403** [manuelcortez/TWBlue#357]
I tried launching twBlue from the latest source in the next-gen branch but I can't.
This is the traceback in the "error.log".

Traceback (most recent call last):
  File "main.py", line 145, in <module>
    setup()
  File "main.py", line 67, in setup
    config.setup()
  File "config.py", line 23, in setup
    if float(platform.version()[:2]) >= 10 and app["app-settings"]["load_keymap"] == "default.keymap":
TypeError: 'NoneType' object is not subscriptable

**Comment by Mohamed00** [comment]
Try deleting twblue.conf in the config folder.

**Comment by guredora403** [comment]
I know, but This way the settings will reset and twBlue won't start when the user updates.
twBlue must make the config file compatible.

**Comment by jmdaweb** [comment]
Hi,
This is caused by a recent update which improved proxy support. In order to make your configured copy work again, edit twblue.conf and navigate to the proxy section. Then, update the following values:

* type: remove the string to the right and write a single zero (0).
* port: change it from 0 to 8080.

A config upgrade procedure will be studied to prevent these issues.

**Comment by guredora403** [comment]
twBlue needs to do that automatically. If it doesn't do that, the updated user will not be able to launch it.

**Comment by manuelcortez** [comment]
Hi @guredora403,
I understand your concern, however we won't make TWBlue to update everything automatically because anyway, users will need to rebuild their configuration files once using one of the next updates. At least the Cache database for storing tweets and the proxy settings are changing due to the way we are handling stuff in the recent time. The proxy settings are relatively easy to fix, but the cache database it's not because it would mix twython generated dictionaries with tweepy objects and this will fail.
Also, users updating from a python 2 generated build will likely have to reinstall everything, as some major changes have been done between Python 2.7.7 and Python 3.8.7.
It would be interesting to generate versionned config files, so every time there are changes in those files, we might add code inside TWBlue to handle changes from previous versions. But with this next version, configs will not be the only thing that will break if people don't do a clean install.

**Comment by guredora403** [comment]
I understood that. Isn't it possible to migrate only the settings? If 
the user can migrate the configuration without having to authenticate 
the account again, the burden can be minimized.
