### ISSUE TITLE
Viewing tweet geolocation information doesn't work

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#390]
Hi, viewing the location information in a tweet hasn't worked for some time now. It seems that no matter the tweet, TWBlue always says that there are no results for the coordinates. EarthquakeBot has quite a few examples of geotweets to test with.

**Comment by manuelcortez** [comment]
It seems this is a pygeocoder's issue. I think we would be better by switching to [GeoPy](https://github.com/geopy/geopy) as this is actually supported, active and works.

**Comment by manuelcortez** [comment]
Update: We will be using the Nominatim Geocoder at Geopy. Unfortunately, this relies in OpenStreetMap, which might not have the same amount of data that Google has. Using google would be possible only if we use a google API key for the maps platform, but I don't think this could be done for the project due to costs associated with those kind of API'S. In the Account @Mohamed00 provided as an example, there were many addresses that the nominatim API simply doesn't have in its database, although for addresses posted from Tweets or apps like Swarm it seems to work more reliably.
