### ISSUE TITLE
Cannot authenticate TWBlue

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#409]
Hi, it looks like as of a few minutes ago, TWBlue seems to be unable to authenticate properly. When I try to add an account, the browser window doesn't open, and a "Could not authenticate you" error is written to the log.

**Comment by manuelcortez** [comment]
Hi, It has happened due to a change in our API keys in Twitter. I have built a new version with the new set of keys. However, I will take a couple hours to update the sources as we are currently researching about how to place the keys here in a safe way. If you are interested, here are the links to download the newest version:
portable 32 bits: https://twblue.es/pubs/twblue_x86.zip
portable 64 bits: https://twblue.es/pubs/twblue_x64.zip
Installer: https://twblue.es/pubs/twblue_setup.exe

**Comment by Mohamed00** [comment]
I noticed that the source fails to launch, with n error stating that it's unable to find a module called appkeys. Is this intentional? I'm asking because I'm interested in testing the improved conversation support.

**Comment by manuelcortez** [comment]
for now sadly it is. As the New Twitter API V2 has clearly stated they are going to apply app quotas and stuff, I want to make sure we are the only project using those keys. Plus it wouldn't be safe if someone else can get those keys in a search in google and stuff. Probably I'll put those in a module and will build it with cython. I mean I don't want to avoid that people could see those keys (It is partially impossible if we want to not force everyone to create their own Twitter keys, although I have been thinking about this btw), but I'd like to make it not so easy for anyone searching in the repo to find those keys.
currently what we do is that the Ci runner, when building the project, adds the module appkeys. I'll try to come up with something interesting tomorrow or so.
