### ISSUE TITLE
TWBlue as a custom Twitter application

### ISSUE THREAD

**Issue by pawelurbanski** [manuelcortez/TWBlue#457]
Hi Manuel,
I would like to ask how TWBlue is registered with Twitter. Is it possible to register it under ones own account after generating developer keys?

All the best...

**Comment by manuelcortez** [comment]
Hi, in theory it is feasible, although we rely in our own keys because Twitter has already lifted us some limits (that's partly the reason why some other clients have issues when creating too many buffers at once, for example) and they no longer are lifting those limits in API V1. So, you can replace the module appkeys.py with your own, but if you give TWBlue a lot of requests to Twitter it might fail due to the API being too limited.
