### ISSUE TITLE
Mastodon: Unable to reply to a toot from the notifications buffer.

### ISSUE THREAD

**Issue by trypsynth** [manuelcortez/TWBlue#517]
Pretty much exactly what it sounds like. I focused a notification that someone mentioned me, but I couldn't reply to it. Log shows nothing, so I assume this is just not implemented. It would be nice if you could add it, though.

**Comment by trypsynth** [comment]
@manuelcortez, updates on this? Not being able to do anything from the notifications buffer is seriously hendering my ability to use Mastodon with TW Blue efficiently.

**Comment by braillescreen** [comment]
+1. Would be amazing.

**Comment by Arfs6** [comment]
Mention notifications are been added to the mentions buffer. i.e. If you someone mentions you in a post, it will show in the notification buffer that someone has mentioned you and in the mentions buffer, it will show the post. You can interact with it in the mentions buffer. 
If we would want to implement interacting with notifications in the notification buffer, then the UI would have to change. Because not all notifications are equal. e.g. Mentions notifications are like posts and follow notifications have actions related to user..
@manuelcortez what do you think?

**Comment by Arfs6** [comment]
I think I have figured out how to solve this. The status dict is added to the notification dict. So, we can use it to interact with the post.
