### ISSUE TITLE
keymaps are not user-writable

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#53]
Due to permissions in installed copies of TWBlue, the keymaps directory cannot be written to by standard (non-administrative) users on modern Windows systems. How can we fix this?

**Comment by manuelcortez** [comment]
If you copy a keymap in the config folder, then you instantiate the keymap from Python using that file, it will allow to modify the keymap (because the config folder is saved in the %appdata% folder) and the modified keymap will not affect the original. I'm working in fixing some other bugs (the #49 bug and some connection errors) so I can't work on this inmediately.
