### ISSUE TITLE
Mastodon: content warning in buffer home

### ISSUE THREAD

**Issue by jeremyp3** [manuelcortez/TWBlue#530]
hello,

I've been wondering about this for a while.

when we receive jets from TWblue for commits made on github, instead of having the text of the commit and the link, we just have the following text:
"TWBlue, Content warning: TWBlue commit. 28 minutes ago. Not listed."

Can we correct this in TWBlue, to have directly the text of the pouet, and not to be forced to display it with win + alt + v ?

Another question, what is this "content warning" for? 

Thanks,

Jeremyp3

**Comment by Mohamed00** [comment]
This is intentional, for those who may not want to see the commits. If 
you want to expand content warnings, you can either set the option in 
your instance's preferences, or go into the account settings, uncheck 
Read preferences from instance, then go into the templates tab, and 
replace $safe_text with just $text.

**Comment by jeremyp3** [comment]
Thank for this very complete answer!

I activated the option in the preferences of my instance and it works immediately much better!
