### ISSUE TITLE
Twitter still works in old builds

### ISSUE THREAD

**Issue by sanslash332** [manuelcortez/TWBlue#549]
As the title says, Just for  curiosity I've launched my old installation of twblue to check if twitter still works.
Interesting surprise; it works with major of the basic functions without any problem.

I know what its the state of twitter with third party applications at today, and that exist restricted access for them to various functions, but... If the basic still works... Why its droped twitter support from twblue?

I know that mastodon will be the new focus of the application, but... Why drop the old support?
It Would have been very interesting if you kept twitter support on the application while the new features for mastodon are added. but well.

If is possible for these people that wants still using twitter (with bad support) can you put on the readme file of this repo a link to the latest release will twitter support?
And of course alert that the new versions dont  support twitter. Somebody that still uses twitter could inadvertently update he's program and well. Give the surprise at the end of the process that the new version dont support twitter. 

Thanks

**Comment by jeremyp3** [comment]
Hello,

If we don't know why it works, and for how long, I think it's pointless 
to make people falsely happy.

Nobody knows where twitter is going, not even twitter itself. TWBlue has 
decided to abandon support for twitter, because the network has become 
unstable. You've seen that twitter is working today, so that's good 
news. But it may not be working again on Monday, so I don't think 
there's any point in re-implementing twitter in TWBlue at the moment, as 
long as we don't know anything about the future of this social network.

**Comment by sanslash332** [comment]
I know how is working twitter now; the point is. Why drop the twitter functions on the main program?

I know that you want to add mastodon that is stable and secure at today, but; why delete the twitter options?

Its obvious that you pause any development over twitter until it be stable again, but one thing is pause the development and oficial support, and other drop all features that well, can works sometimes.

But I understand what is the approach; you don't want to kept any unstable functionality on the program that can works some day, and fails another. Comprehensible.

The just that I said, is that you can put some notice on the readme, saying which is the latest version that still works with twitter if somebody is looking for it.

That was my case, for example. I've the luck that I found a old version in my computer; if that wasn't the case, I couldn't found that version.

**Comment by manuelcortez** [comment]
Hi @sanslash332. I will not add any code regarding Twitter until we have an answer about what's going on. You're probably ignoring that we did not dropped Twitter support because it's not unstable. We did it because we, as well as other twitter clients, were dropped completely from their authorization Site and so far, any third party client is violating their platform rules. I see no point on keeping code and dependencies into things that are not going to work "officially". I'll think about rebuilding the latest version that still Supported Twitter and putting it somewhere available for the world, but this idea of we don't adding Twitter compatible code because "the platform is unstable" is not true, sorry. If you want more details, take a look here: https://www.theverge.com/2023/1/19/23562947/twitter-third-party-client-tweetbot-twitterific-ban-rules

**Comment by sanslash332** [comment]
Hello @manuelcortez 
Um, maybe my words were unclear.
When I said unstable, I was not talking about the stability of the program or the API it self, but I was talking about the problems with the third party applications and their legality on their current platform rules that at today, they are completely unclear.

I know that current the third apps are prohibited, but if their are ilegal... Why their api is still open? and why the users can authorize new apps?

You could still working on that legal gray area, but I know that you prefer go fully over the legal way to don't have problems in the future. That was really the question; regarding than be ilegal or unclear the current situation, it still works, so somebody that don't care about the twitter things, can use the application through that  legal hole that twiter keeps today. So for these people keep the old version could be a good idea, obviousli warning that program could stop working on any moment and maybe the account could habe problems if twitter decide that.

Thanks :-)
