### ISSUE TITLE
new twblue executable on the website

### ISSUE THREAD

**Issue by Arfs6** [manuelcortez/TWBlue#556]
The last version of twblue on the website is from february. When will a new version be uploaded?
Since twblue is on github, you can make the download page download it from github releases. That means we need to have releases here on github.

**Comment by rkingett** [comment]
Is the portable version links evergreen as well or are they pointing to old versions too?

**Comment by manuelcortez** [comment]
I'll move TWBlue to be built on GH actions later in this year. Probably then, I'll be able to use github downloads right here, although I'm still not sure about this. The problem is not about where to host the executables, I think it's more related to my recent lack of time and probably need for more documented release processes.
