### ISSUE TITLE
github workflow for releases

### ISSUE THREAD

**Issue by Arfs6** [manuelcortez/TWBlue#561]
I started working on a github workflow for automating tw blue releases.
When installing packages from pip listed in requirements.txt, I get an error. It is from pillow. It says pillow needs zlib library to build the wheels. The error is only for 32 bit. After doing some digging, I learned pillow stopped building 32 bit wheels.
I haven't figured out how to install the zlib library yet but should we go the building route? Should we build our pillow on the runners? NSIS needs the 32 bit binary to generate the intaller.

**Comment by manuelcortez** [comment]
Hi , long time without being here. Hopefully I will have more time till the end of the year. I am wondering wether we should keep building for 32bit platform as it seems mostly everyone use 64bit already. Currently we do some exceptions for 32bit, as we use wxpython from a git repository as opposed to PIP builds because wx itself is only built against x64.

**Comment by Arfs6** [comment]
I think dropping the support for 32 bits make sense, the list of packages that will not build wheels for 32 bits will just grow with time, and building all the packages wouldn't be feasible.
For the users that need the 32 bits TW Blue, we should update our README to make the experience much more straight forward.

If this is the path we're going to take, the nsis script for building the installer needs to be updated. After the update then the release github actions will be created.

**Comment by Arfs6** [comment]
This issue should be closed as #567 has been merged.
