### ISSUE TITLE
[Enhancement] Support for Deleted Tweets

### ISSUE THREAD

**Issue by trodick** [manuelcortez/TWBlue#69]
I would like to suggest the following enhancement, which would conform to this specification:
1. The application will be connected to the Twitter streaming API, receiving and handling events.
2. One such event that will be handled will be the event which is triggered when a user deletes a tweet.
3. OnTweetDeleted: buffers.search for the respective tweet by ID. Tweet is removed from all buffers in which it is found. A sound is played to indicate this fact.

**Comment by manuelcortez** [comment]
I implemented it in [This commit](https://github.com/manuelcortez/TWBlue/commit/92d803717f5550a26b7de79484e2dd5c59ef09cd) However I have to check if it works for everyone and people with multiple account, so I think I can't close this issue right now. If everything works as expected, I'll close it.

**Comment by codeofdusk** [comment]
This enhancement should definitely be optional, as some people do not want to have tweets deleted from their clients.

Bill

**Comment by manuelcortez** [comment]
Well, I partially agree. Currently tweets are not deleted from clients when someone deletes an item, but people can't view that tweet (by pressing control+win+v and so) because TWBlue tries to get the tweet object again  for displaying the correct stats (favourites and retweets, for example). Of course if the tweet doesn't exist, you will hear an error and nothing will happen. But I think that if we will make this optional, we could change that behaviour, for  example, you could see a dialogue where TWBlue says that you are viewing an already deleted tweet but it remains in your client, or something like that.

**Comment by codeofdusk** [comment]
+1
